### ISSUE TITLE
Menu item doesn't show up in web solutions

### ISSUE THREAD

**Issue by robsiera** [seldary/Ersx.Net#1]
Your plug-in works great, but only in web projects the context menu items doesn't show up. 
Is there a workaround for that?

Or maybe it doesn't have anything to do with being a web project?
How do you decide if a file is a resx? By looking at the Extention? Then it should work (but doesn't).

**Comment by seldary** [comment]
I just tested the extension with a resource.resx file inside a WebApplication project - seems ok.
Can you share your VS version, what type of project you added, and anything else that's different between the two projects?

The "Sort Resx" menu item appears if at least one of the selected files ends with ".resx".
You can also take a look at the output window for errors...

Thanks

**Comment by robsiera** [comment]
I'm using VS2013
You can test is with this github project https://github.com/dnnsoftware/Dnn.Platform.
This solution https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN_Platform.sln
will load this website https://github.com/dnnsoftware/Dnn.Platform/tree/development/Website
and the resx files are in this folder https://github.com/dnnsoftware/Dnn.Platform/tree/development/Website/App_GlobalResources
I hope that helps.
